'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class LocalizedMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DataTools.Interop.LocalizedMessages", GetType(LocalizedMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to register application for restart due to bad parameters..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoverFailedToRegisterForRestartBadParameters() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoverFailedToRegisterForRestartBadParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application was not registered for recovery due to bad parameters..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryBadParameters() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryBadParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application failed to register for recovery..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryFailedToRegister() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryFailedToRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application failed to registered for restart..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryFailedToRegisterForRestart() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryFailedToRegisterForRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unregister for recovery failed..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryFailedToUnregister() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryFailedToUnregister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unregister for restart failed..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryFailedToUnregisterForRestart() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryFailedToUnregisterForRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This method must be called from the registered callback method..
        '''</summary>
        Public Shared ReadOnly Property ApplicationRecoveryMustBeCalledFromCallback() As String
            Get
                Return ResourceManager.GetString("ApplicationRecoveryMustBeCalledFromCallback", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ACOnline: {1}{0}Max Charge: {2} mWh{0}Current Charge: {3} mWh{0}Discharge Rate: {4} mWh{0}Estimated Time Remaining: {5}{0}Suggested Critical Battery Charge: {6} mWh{0}Suggested Battery Warning Charge: {7} mWh{0}.
        '''</summary>
        Public Shared ReadOnly Property BatteryStateStringRepresentation() As String
            Get
                Return ResourceManager.GetString("BatteryStateStringRepresentation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelable cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property CancelableCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("CancelableCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog caption cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property CaptionCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("CaptionCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CheckBox text cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property CheckBoxCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("CheckBoxCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Collapsed control text cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property CollapsedTextCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("CollapsedTextCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only supported on Windows 7 or newer..
        '''</summary>
        Public Shared ReadOnly Property CoreHelpersRunningOn7() As String
            Get
                Return ResourceManager.GetString("CoreHelpersRunningOn7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only supported on Windows 8 or newer..
        '''</summary>
        Public Shared ReadOnly Property CoreHelpersRunningOn8() As String
            Get
                Return ResourceManager.GetString("CoreHelpersRunningOn8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only supported on Windows 8.1 or newer..
        '''</summary>
        Public Shared ReadOnly Property CoreHelpersRunningOn81() As String
            Get
                Return ResourceManager.GetString("CoreHelpersRunningOn81", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only supported on Windows Vista or newer..
        '''</summary>
        Public Shared ReadOnly Property CoreHelpersRunningOnVista() As String
            Get
                Return ResourceManager.GetString("CoreHelpersRunningOnVista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only supported on Windows XP or newer..
        '''</summary>
        Public Shared ReadOnly Property CoreHelpersRunningOnXp() As String
            Get
                Return ResourceManager.GetString("CoreHelpersRunningOnXp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog cannot have more than one control with the same name..
        '''</summary>
        Public Shared ReadOnly Property DialogCollectionCannotHaveDuplicateNames() As String
            Get
                Return ResourceManager.GetString("DialogCollectionCannotHaveDuplicateNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog control must be removed from current collections first..
        '''</summary>
        Public Shared ReadOnly Property DialogCollectionControlAlreadyHosted() As String
            Get
                Return ResourceManager.GetString("DialogCollectionControlAlreadyHosted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Control name cannot be null or zero length..
        '''</summary>
        Public Shared ReadOnly Property DialogCollectionControlNameNull() As String
            Get
                Return ResourceManager.GetString("DialogCollectionControlNameNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modifying controls collection while dialog is showing is not supported..
        '''</summary>
        Public Shared ReadOnly Property DialogCollectionModifyShowingDialog() As String
            Get
                Return ResourceManager.GetString("DialogCollectionModifyShowingDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog control name cannot be empty or null..
        '''</summary>
        Public Shared ReadOnly Property DialogControlNameCannotBeEmpty() As String
            Get
                Return ResourceManager.GetString("DialogControlNameCannotBeEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog controls cannot be renamed..
        '''</summary>
        Public Shared ReadOnly Property DialogControlsCannotBeRenamed() As String
            Get
                Return ResourceManager.GetString("DialogControlsCannotBeRenamed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application.
        '''</summary>
        Public Shared ReadOnly Property DialogDefaultCaption() As String
            Get
                Return ResourceManager.GetString("DialogDefaultCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property DialogDefaultContent() As String
            Get
                Return ResourceManager.GetString("DialogDefaultContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property DialogDefaultMainInstruction() As String
            Get
                Return ResourceManager.GetString("DialogDefaultMainInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expanded information mode cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property ExpandedDetailsCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("ExpandedDetailsCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expanded control label cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property ExpandedLabelCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("ExpandedLabelCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expanding state of the dialog cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property ExpandingStateCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("ExpandingStateCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hyperlinks cannot be enabled/disabled while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property HyperlinksCannotBetSet() As String
            Get
                Return ResourceManager.GetString("HyperlinksCannotBetSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference path is invalid..
        '''</summary>
        Public Shared ReadOnly Property InvalidReferencePath() As String
            Get
                Return ResourceManager.GetString("InvalidReferencePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified event handler has not been registered..
        '''</summary>
        Public Shared ReadOnly Property MessageManagerHandlerNotRegistered() As String
            Get
                Return ResourceManager.GetString("MessageManagerHandlerNotRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occurred in dialog configuration..
        '''</summary>
        Public Shared ReadOnly Property NativeTaskDialogConfigurationError() As String
            Get
                Return ResourceManager.GetString("NativeTaskDialogConfigurationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid arguments to Win32 call..
        '''</summary>
        Public Shared ReadOnly Property NativeTaskDialogInternalErrorArgs() As String
            Get
                Return ResourceManager.GetString("NativeTaskDialogInternalErrorArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog contents too complex..
        '''</summary>
        Public Shared ReadOnly Property NativeTaskDialogInternalErrorComplex() As String
            Get
                Return ResourceManager.GetString("NativeTaskDialogInternalErrorComplex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected internal error occurred in the Win32 call: {0:x}.
        '''</summary>
        Public Shared ReadOnly Property NativeTaskDialogInternalErrorUnexpected() As String
            Get
                Return ResourceManager.GetString("NativeTaskDialogInternalErrorUnexpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TaskDialog feature needs to load version 6 of comctl32.dll but a different version is current loaded in memory..
        '''</summary>
        Public Shared ReadOnly Property NativeTaskDialogVersionError() As String
            Get
                Return ResourceManager.GetString("NativeTaskDialogVersionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog owner cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property OwnerCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("OwnerCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SetThreadExecutionState call failed..
        '''</summary>
        Public Shared ReadOnly Property PowerExecutionStateFailed() As String
            Get
                Return ResourceManager.GetString("PowerExecutionStateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The caller had insufficient access rights to get the system battery state..
        '''</summary>
        Public Shared ReadOnly Property PowerInsufficientAccessBatteryState() As String
            Get
                Return ResourceManager.GetString("PowerInsufficientAccessBatteryState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The caller had insufficient access rights to get the system power capabilities..
        '''</summary>
        Public Shared ReadOnly Property PowerInsufficientAccessCapabilities() As String
            Get
                Return ResourceManager.GetString("PowerInsufficientAccessCapabilities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get active power scheme..
        '''</summary>
        Public Shared ReadOnly Property PowerManagerActiveSchemeFailed() As String
            Get
                Return ResourceManager.GetString("PowerManagerActiveSchemeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery is not present on this system..
        '''</summary>
        Public Shared ReadOnly Property PowerManagerBatteryNotPresent() As String
            Get
                Return ResourceManager.GetString("PowerManagerBatteryNotPresent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress bar cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property ProgressBarCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("ProgressBarCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress bar cannot be hosted in multiple dialogs..
        '''</summary>
        Public Shared ReadOnly Property ProgressBarCannotBeHostedInMultipleDialogs() As String
            Get
                Return ResourceManager.GetString("ProgressBarCannotBeHostedInMultipleDialogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}, {1}.
        '''</summary>
        Public Shared ReadOnly Property PropertyKeyFormatString() As String
            Get
                Return ResourceManager.GetString("PropertyKeyFormatString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to initialize PropVariant..
        '''</summary>
        Public Shared ReadOnly Property PropVariantInitializationError() As String
            Get
                Return ResourceManager.GetString("PropVariantInitializationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multi-dimensional SafeArrays not supported..
        '''</summary>
        Public Shared ReadOnly Property PropVariantMultiDimArray() As String
            Get
                Return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to String argument cannot be null or empty..
        '''</summary>
        Public Shared ReadOnly Property PropVariantNullString() As String
            Get
                Return ResourceManager.GetString("PropVariantNullString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Value type is not supported..
        '''</summary>
        Public Shared ReadOnly Property PropVariantTypeNotSupported() As String
            Get
                Return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot be cast to unsupported type..
        '''</summary>
        Public Shared ReadOnly Property PropVariantUnsupportedType() As String
            Get
                Return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delegate: {0}, state: {1}, ping: {2}.
        '''</summary>
        Public Shared ReadOnly Property RecoverySettingsFormatString() As String
            Get
                Return ResourceManager.GetString("RecoverySettingsFormatString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to command: {0} restrictions: {1}.
        '''</summary>
        Public Shared ReadOnly Property RestartSettingsFormatString() As String
            Get
                Return ResourceManager.GetString("RestartSettingsFormatString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StandardButtons cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property StandardButtonsCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("StandardButtonsCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup location cannot be changed while dialog is showing..
        '''</summary>
        Public Shared ReadOnly Property StartupLocationCannotBeChanged() As String
            Get
                Return ResourceManager.GetString("StartupLocationCannotBeChanged", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad button ID in closing event..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogBadButtonId() As String
            Get
                Return ResourceManager.GetString("TaskDialogBadButtonId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Button text must be non-empty..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogButtonTextEmpty() As String
            Get
                Return ResourceManager.GetString("TaskDialogButtonTextEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check box text must be provided to enable the dialog check box..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogCheckBoxTextRequiredToEnableCheckBox() As String
            Get
                Return ResourceManager.GetString("TaskDialogCheckBoxTextRequiredToEnableCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attempting to close a non-showing dialog..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogCloseNonShowing() As String
            Get
                Return ResourceManager.GetString("TaskDialogCloseNonShowing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application.
        '''</summary>
        Public Shared ReadOnly Property TaskDialogDefaultCaption() As String
            Get
                Return ResourceManager.GetString("TaskDialogDefaultCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property TaskDialogDefaultContent() As String
            Get
                Return ResourceManager.GetString("TaskDialogDefaultContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property TaskDialogDefaultMainInstruction() As String
            Get
                Return ResourceManager.GetString("TaskDialogDefaultMainInstruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot have more than one default button of a given type..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogOnlyOneDefaultControl() As String
            Get
                Return ResourceManager.GetString("TaskDialogOnlyOneDefaultControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum value provided must be greater than the minimum value..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogProgressBarMaxValueGreaterThanMin() As String
            Get
                Return ResourceManager.GetString("TaskDialogProgressBarMaxValueGreaterThanMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum value provided must be a positive number..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogProgressBarMinValueGreaterThanZero() As String
            Get
                Return ResourceManager.GetString("TaskDialogProgressBarMinValueGreaterThanZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum value provided must less than the maximum value..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogProgressBarMinValueLessThanMax() As String
            Get
                Return ResourceManager.GetString("TaskDialogProgressBarMinValueLessThanMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value provided must be greater than equal to the minimum value and less than the maximum value..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogProgressBarValueInRange() As String
            Get
                Return ResourceManager.GetString("TaskDialogProgressBarValueInRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog cannot display both non-standard buttons and standard buttons..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogSupportedButtonsAndButtons() As String
            Get
                Return ResourceManager.GetString("TaskDialogSupportedButtonsAndButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dialog cannot display both non-standard buttons and command links..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogSupportedButtonsAndLinks() As String
            Get
                Return ResourceManager.GetString("TaskDialogSupportedButtonsAndLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown dialog control type..
        '''</summary>
        Public Shared ReadOnly Property TaskDialogUnkownControl() As String
            Get
                Return ResourceManager.GetString("TaskDialogUnkownControl", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
